# RawNet3 reproduce recipe configuration.
encoder: rawnet3
encoder_conf: 
  a: 1
  b: 2

model_conf:
  loss: a

projector: rawnet3
projector_conf:
  input_size: 2048
  output_size: 256


preprocessor: spk
