# Model
model: espnet
model_conf:
    share_emb: false
  
corelm: ar
corelm_conf:
    pos_enc: sinusoidal
    att_unit: 512
    head: 8
    unit: 1024
    decoder_layer: 12
    dropout_rate: 0.0
    positional_dropout_rate: 0.0
    attention_dropout_rate: 0.0
    flashattention: true

predictor: parallel
postprocessor: none

# Dataloader
batch_type: numel
batch_bins: 40000
accum_grad: 1
grad_clip: 2
max_epoch: 100
num_workers: 4
log_interval: 500

# Criterion & Optimization
optim: adamw
optim_conf:
    lr: 0.0003
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 7000
best_model_criterion:
-   - valid
    - acc
    - max
-   - valid
    - loss
    - min
keep_nbest_models: 10

# Global settings
use_amp: true
encoder_decoder_format: false
codec_token_per_frame: 8 # encodec
codec_token_in_use: 8
speaker_prompt_length: 225 # 75fps, a.k.a., 3s
