# RawNet3 reproduce recipe configuration.
frontend: raw

encoder: rawnet3
encoder_conf:  # uncomment for customized arguments
  model_scale: 4
  ndim: 64

pooling: chn_attn_stat
pooling_conf:
  input_size: 96

projector: rawnet3
projector_conf:
  input_size: 192
  output_size: 16

preprocessor: spk
preprocessor_conf:
  target_duration: 3.0  # seconds
  sample_rate: 16000
  num_eval: 1
  noise_apply_prob: 0.0

model_conf:
  extract_feats_in_collect_stats: false

loss: aamsoftmax
loss_conf:
  nOut: 16
  nClasses: 108
  margin: 0.3
  scale: 15

optim: adam
num_att_plot: 0
