# ECAPA-TDNN reproduce recipe configuration.

# Frontend
frontend: default
frontend_conf:
    hop_length: 128
    n_mels: 80

# Normalizer
normalize: utterance_mvn
normalize_conf:
    norm_vars: false

# Encoder
encoder: ecapa_tdnn
encoder_conf:
  model_scale: 8
  ndim: 1024
  output_size: 1536

# Pooling
pooling: chn_attn_stat

# Projector
projector: rawnet3
projector_conf:
  output_size: 256

# Preprocessor
preprocessor: spk
preprocessor_conf:
  target_duration: 3.0  # seconds
  sample_rate: 16000
  num_eval: 5
  noise_apply_prob: 0.5
  noise_info:
  - [1.0, '/scratch/bbjs/shared/corpora/voxcelebs/musan_speech.scp', [4, 7], [13, 20]]
  - [1.0, '/scratch/bbjs/shared/corpora/voxcelebs/musan_noise.scp', [1, 1], [0, 15]]
  - [1.0, '/scratch/bbjs/shared/corpora/voxcelebs/musan_music.scp', [1, 1], [5, 15]]
  rir_apply_prob: 0.5
  rir_scp: /scratch/bbjs/shared/corpora/voxcelebs/rirs.scp

# Model conf
model_conf:
  extract_feats_in_collect_stats: false

# Loss
loss: aamsoftmax
loss_conf:
  margin: 0.3
  scale: 30

# Training related
max_epoch: 160
num_att_plot: 0
num_workers: 8
cudnn_deterministic: False
cudnn_benchmark: True
iterator_type: category
valid_iterator_type: sequence
shuffle_within_batch: False
log_interval: 100
batch_size: 512
valid_batch_size: 40
best_model_criterion:
- - valid
  - eer
  - min

# Optimizer
optim: adam
optim_conf:
  lr: 0.001
  weight_decay: 0.00005
  amsgrad: False

# Scheduler
scheduler: CosineAnnealingWarmupRestarts
scheduler_conf:
  first_cycle_steps: 73024
  cycle_mult: 1.0
  max_lr: 0.001
  min_lr: 0.000005
  warmup_steps: 1000
  gamma: 0.7
