# RawNet3 reproduce recipe configuration.

# Frontend
frontend: asteroid_frontend
frontend_conf:
    sinc_stride: 16
    sinc_kernel_size: 251
    sinc_filters: 256
    preemph_coef: 0.97
    log_term: 0.000001

# Encoder
encoder: rawnet3
encoder_conf:
  model_scale: 8
  ndim: 1024
  output_size: 1536

# Pooling
pooling: chn_attn_stat

# Projector
projector: rawnet3
projector_conf:
  output_size: 256

preprocessor: spk
preprocessor_conf:
  target_duration: 3.0  # seconds
  sample_rate: 16000
  num_eval: 5
  noise_apply_prob: 0.0
  rir_apply_prob: 0.0

# Model conf
model_conf:
  extract_feats_in_collect_stats: false

# Loss
loss: aamsoftmax
loss_conf:
  margin: 0.3
  scale: 30

# Training related
max_epoch: 40
num_att_plot: 0
num_workers: 0
cudnn_deterministic: False
cudnn_benchmark: True
batch_size: 128
iterator_type: sequence
shuffle_within_batch: True
log_interval: 50

# Optimizer
optim: adamw
optim_conf:
  lr: 0.001
  weight_decay: 0.00005
  amsgrad: False

# Scheduler
scheduler: CosineAnnealingWarmupRestarts
scheduler_conf:
  first_cycle_steps: 77544
  cycle_mult: 1.0
  max_lr: 0.001
  min_lr: 0.000005
  warmup_steps: 1000
  gamma: 0.75
