# ECAPA-TDNN reproduce recipe configuration.

# Frontend
frontend: default
frontend_conf:
    win_length: 400
    hop_length: 160
    n_mels: 80
    window: hamming

# Normalizer
normalize: utterance_mvn
normalize_conf:
    norm_vars: false

# Encoder
encoder: mfa_conformer
encoder_conf:
  output_size: 512
  attention_heads: 8
  linear_units: 2048
  num_blocks: 6
  dropout_rate: 0.1
  positional_dropout_rate: 0.1
  attention_dropout_rate: 0.1
  input_layer: conv2d2
  normalize_before: true
  macaron_style: true
  rel_pos_type: latest
  pos_enc_layer_type: rel_pos
  selfattention_layer_type: rel_selfattn
  activation_type: swish
  use_cnn_module: true
  cnn_module_kernel: 15

# Pooling
pooling: chn_attn_stat

# Projector
projector: rawnet3
projector_conf:
  output_size: 192

# Preprocessor
preprocessor: spk
preprocessor_conf:
  target_duration: 3.0  # seconds
  sample_rate: 16000
  num_eval: 5
  noise_apply_prob: 0.5
  noise_info:
  - [1.0, 'dump/raw_copy/musan_speech.scp', [4, 7], [13, 20]]
  - [1.0, 'dump/raw_copy/musan_noise.scp', [1, 1], [0, 15]]
  - [1.0, 'dump/raw_copy/musan_music.scp', [1, 1], [5, 15]]
  rir_apply_prob: 0.5
  rir_scp: dump/raw_copy/rirs.scp

# Model conf
model_conf:
  extract_feats_in_collect_stats: false

# Loss
loss: aamsoftmax
loss_conf:
  margin: 0.3
  scale: 30

# Training related
max_epoch: 40
num_att_plot: 0
num_workers: 8
cudnn_deterministic: False
cudnn_benchmark: True
iterator_type: category
valid_iterator_type: sequence
shuffle_within_batch: False
log_interval: 100
batch_size: 200
valid_batch_size: 32
best_model_criterion:
- - valid
  - eer
  - min

# Optimizer
optim: adam
optim_conf:
  lr: 0.001
  weight_decay: 0.00005
  amsgrad: False

# Scheduler
scheduler: CosineAnnealingWarmupRestarts
scheduler_conf:
<<<<<<< Updated upstream
  first_cycle_steps: 129848
  cycle_mult: 1.0
  max_lr: 0.001
  min_lr: 0.0000001
  warmup_steps: 10000
  gamma: 0.7
=======
  first_cycle_steps: 62490
  cycle_mult: 1.0
  max_lr: 0.001
  min_lr: 0.0000001
  warmup_steps: 2000
  gamma: 0.75
>>>>>>> Stashed changes

unused_parameters: True
grad_clip: 9999
