# RawNet3 reproduce recipe configuration.

# Frontend
frontend: asteroid_frontend
frontend_conf:
    sinc_stride: 16
    sinc_kernel_size: 251
    sinc_filters: 256
    preemph_coef: 0.97
    log_term: 1e-6

# Encoder
encoder: rawnet3
encoder_conf:
  model_scale: 8
  ndim: 1024
  output_size: 1536

# Pooling
pooling: chn_attn_stat

# Projector
projector: rawnet3
projector_conf:
  output_size: 256

# Preprocessor
preprocessor: spk
preprocessor_conf:
  target_duration: 3.0
  sr: 16000
  num_eval: 5
  noise_apply_prob: 0.0
  rir_apply_prob: 0.0

# Model conf
model_conf:
  extract_feats_in_collect_stats: false

# Loss
loss: aamsoftmax
loss_conf:
  margin: 0.2
  scale: 15

# Training related
optim: adam
max_epoch: 40
num_att_plot: 0
num_workers: 6
cudnn_deterministic: False
cudnn_benchmark: True
batch_size: 32
iterator_type: sequence
shuffle_within_batch: True
log_interval: 50
