# This is a debug config for CI
encoder: stft
encoder_conf:
    n_fft: 512
    hop_length: 128

decoder: stft
decoder_conf:
    n_fft: 512
    hop_length: 128

separator: rnn
separator_conf:
    rnn_type: blstm
    num_spk: 1
    nonlinear: relu
    layer: 1
    unit: 2
    dropout: 0.2

criterions:
  # The first criterion
  - name: mse
    conf:
      compute_on_mask: True
      mask_type: PSM^2
    # the wrapper for the current criterion
    # for single-talker case, we simplely use fixed_order wrapper
    wrapper: fixed_order
    wrapper_conf:
      weight: 1.0

max_epoch: 1
num_iters_per_epoch: 1
batch_type: folded
batch_size: 2
iterator_type: chunk
chunk_length: 50 # 1s
chunk_default_fs: 50 # GCD among all possible sampling frequencies
chunk_max_abs_length: 100000 # max number of samples per chunk for all sampling frequencies (reduce this value if OOM occurs)
chunk_discard_short_samples: false
