# network architecture

# encoder related
encoder: transformer_multispkr
encoder_conf:
    output_size: 256
    attention_heads: 4
    linear_units: 2048
    num_blocks: 8
    num_blocks_sd: 4
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.1
    input_layer: conv2d
    normalize_before: true
    num_inf: 2

# decoder related
decoder: transformer
decoder_conf:
    attention_heads: 4
    linear_units: 2048
    num_blocks: 6
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    self_attention_dropout_rate: 0.1
    src_attention_dropout_rate: 0.1

# ctc related
ctc_conf:
    reduce: false

model: pit_espnet
model_conf:
    ctc_weight: 0.2
    lsm_weight: 0.1
    length_normalized_loss: false
    num_inf: 2
    num_ref: 2

# preprocessor related
preprocessor: multi
preprocessor_conf:
    text_name:
        - "text"           # no suffix for the first text
        - "text_spk2"

# minibatch related
num_workers: 8
batch_type: numel
batch_bins: 4000000
accum_grad: 4
max_epoch: 60
patience: none
init: none
best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 10

optim: adam
optim_conf:
    lr: 0.0005
    weight_decay: 0.000001
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 20000

specaug: null
